#!/bin/env python3

import re
import binascii
from io import StringIO
from tempfile import TemporaryFile
from protobuf_inspector.types import StandardParser

REGEX = r"(\\x0a\\x12.*)?\","
parser = StandardParser()

with open('strace.txt') as f:
    data = f.read()

#for match in re.search(REGEX, data):
#    print(match.strip())
#    from time import sleep
#    sleep(5)
results = re.findall(REGEX, data)

for msg in results:
    if msg == '':
        continue
    tmp = TemporaryFile()
    tmp.write(binascii.unhexlify(msg.replace('\\x', '')))
    tmp.seek(0)
    decoded = parser.parse_message(tmp, 'message')

    print('-' * 80)
    print(f'Strace: {msg}')
    print(f'Decoded: {decoded}')
