#!/bin/env python3

import os
import re
import sys
import binascii
from tempfile import TemporaryFile
from protobuf_inspector.types import StandardParser

REGEX = r"(\\x0a\\x12.*)?\","
parser = StandardParser()

if len(sys.argv) != 2:
    print('Usage: decoder <file>')
    sys.exit(1)

strace_file = sys.argv[1]
if not os.path.exists(strace_file):
    print(f'File "{strace_file}" does not exist!')
    sys.exit(2)

with open(strace_file) as f:
    data = f.read()

results = re.findall(REGEX, data)
for msg in results:
    if msg == '':
        continue
    tmp = TemporaryFile()
    tmp.write(binascii.unhexlify(msg.replace('\\x', '')))
    tmp.seek(0)
    decoded = parser.parse_message(tmp, 'message')

    print('-' * 80)
    print(f'Strace: {msg}')
    print(f'Decoded: {decoded}')
