#!/bin/env python3
#
#    ssc-sensor-proxy: a drop-in replacement for iio-sensor-proxy for SSC support
#    Copyright (C) 2022  Dylan Van Assche
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published
#    by the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#  
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

import os
import re
import sys
import binascii
from tempfile import TemporaryFile
from protobuf_inspector.types import StandardParser

REGEX = r"(\\x0a\\x12.*)?\","
parser = StandardParser()

if len(sys.argv) != 2:
    print('Usage: decoder <file>')
    sys.exit(1)

strace_file = sys.argv[1]
if not os.path.exists(strace_file):
    print(f'File "{strace_file}" does not exist!')
    sys.exit(2)

with open(strace_file) as f:
    data = f.read()

results = re.findall(REGEX, data)
for msg in results:
    if msg == '':
        continue
    tmp = TemporaryFile()
    tmp.write(binascii.unhexlify(msg.replace('\\x', '')))
    tmp.seek(0)
    decoded = parser.parse_message(tmp, 'message')

    print('-' * 80)
    print(f'Strace: {msg}')
    print(f'Decoded: {decoded}')
