/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-gyroscope.proto */

#ifndef PROTOBUF_C_ssc_2dsensor_2dgyroscope_2eproto__INCLUDED
#define PROTOBUF_C_ssc_2dsensor_2dgyroscope_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SscGyroscopeResponse SscGyroscopeResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Gyroscope Sensor specific response data.
 * @velocity: velocity per axis in m/s: X-axis [0], Y-axis [1], Z-axis [2].
 * @accuracy: how reliable the value is [0, 3]. Higher is more accurate, 0 is unreliable.
 */
struct  SscGyroscopeResponse
{
  ProtobufCMessage base;
  size_t n_velocity;
  float *velocity;
  int32_t accuracy;
};
#define SSC_GYROSCOPE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssc_gyroscope_response__descriptor) \
    , 0,NULL, 0 }


/* SscGyroscopeResponse methods */
void   ssc_gyroscope_response__init
                     (SscGyroscopeResponse         *message);
size_t ssc_gyroscope_response__get_packed_size
                     (const SscGyroscopeResponse   *message);
size_t ssc_gyroscope_response__pack
                     (const SscGyroscopeResponse   *message,
                      uint8_t             *out);
size_t ssc_gyroscope_response__pack_to_buffer
                     (const SscGyroscopeResponse   *message,
                      ProtobufCBuffer     *buffer);
SscGyroscopeResponse *
       ssc_gyroscope_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssc_gyroscope_response__free_unpacked
                     (SscGyroscopeResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SscGyroscopeResponse_Closure)
                 (const SscGyroscopeResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssc_gyroscope_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ssc_2dsensor_2dgyroscope_2eproto__INCLUDED */
