/*
 * ssc-sensor-proxy: a drop-in replacement for iio-sensor-proxy for SSC support
 * Copyright (C) 2022 Dylan Van Assche
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
syntax = "proto2";
import "ssc-shared.proto";
package ssc.sensor.proxy;

/*
 * SUID sensor request to retrieve information about available sensors.
 * @sensor_uid: SUID sensor UID (0xABABABABABABABAB 0xABABABABABABABAB), see SscSharedUid.
 * @msg_type: an enum value of SscSharedMsgType.
 * @config: see SscSharedConfig.
 * @request: see SscSuidSensorRequest.
 */
message SscSuidSensorRequestMessage {
	required SscSharedUid sensor_uid = 1;
	required fixed32 msg_type = 2;
	required SscSharedConfig config = 3;
	/* 
	 * SUID Sensor Request.
	 * @data: the sensor specific request data.
	 * 
	 * Since this is a message and the data field has ID 2,
	 * we can assume that there are other fields as well. 
	 * However, they are not reverse-engineered yet.
	 */
	message SscSuidSensorRequest {
		/* 
		 * Sensor specific request data.
		 * @data_type: retrieve all sensors exposing the specified data type.
		 * An empty value will return all sensors.
		 * @enable_updates: setting this to true will enable updates 
		 * for the specified data_type.
		 * @only_default_values: setting this to true will only return 
		 * the default sensor for the data_type, even if multiple sensors expose it.
		 */
		message SscSuidSensorRequestData {
			required string data_type = 1;
			optional bool enable_updates = 2;
			optional bool only_default_values = 3;
		}
		required SscSuidSensorRequestData data = 2;
	}
	required SscSuidSensorRequest request = 4;
}

// ********************************************************************************************** //

/*
 * SUID sensor replies with a list of sensors
 * of the requested data type. The list of sensors
 * contains the UID of each sensor.
 * @sensor_uid: SUID sensor UID (0xABABABABABABABAB 0xABABABABABABABAB).
 * @event: see SscSuidSensorEvent
 */
message SscSuidSensorEventMessage {
	required SscSharedUid sensor_uid = 1;
	/*
	 * SUID Sensor Event.
	 * @msg_type: an enum value of SscSharedMsgType.
	 * @timestamp: a 64bit timestamp from the Hexagon DSP timer.
	 * @data: see SscSuidSensorEventData.
	 */
	message SscSuidSensorEvent {
		required fixed32 msg_type = 1;
		required fixed64 timestamp = 2;
		/*
		 * Sensor specific event data.
		 * @data_type: the data type matching all the listed sensor UIDs.
		 * @sensor_uid: list of matching sensor UIDs, see SscSharedUid.
		 */
		message SscSuidSensorEventData {
			required string data_type = 1;
			repeated SscSharedUid sensor_uid = 2;
		}
		required SscSuidSensorEventData data = 3;
	}
	required SscSuidSensorEvent event = 2;
}
