/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-rotationvector.proto */

#ifndef PROTOBUF_C_ssc_2dsensor_2drotationvector_2eproto__INCLUDED
#define PROTOBUF_C_ssc_2dsensor_2drotationvector_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SscRotationvectorResponse SscRotationvectorResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Rotationvector Sensor specific response data.
 * @rotation: rotation per axis as quaternion: X-axis [0], Y-axis [1], Z-axis [2], W rotation angle [3]
 * @accuracy: how reliable the value is [0, 3]. Higher is more accurate, 0 is unreliable.
 */
struct  SscRotationvectorResponse
{
  ProtobufCMessage base;
  size_t n_rotation;
  float *rotation;
  int32_t accuracy;
};
#define SSC_ROTATIONVECTOR_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssc_rotationvector_response__descriptor) \
    , 0,NULL, 0 }


/* SscRotationvectorResponse methods */
void   ssc_rotationvector_response__init
                     (SscRotationvectorResponse         *message);
size_t ssc_rotationvector_response__get_packed_size
                     (const SscRotationvectorResponse   *message);
size_t ssc_rotationvector_response__pack
                     (const SscRotationvectorResponse   *message,
                      uint8_t             *out);
size_t ssc_rotationvector_response__pack_to_buffer
                     (const SscRotationvectorResponse   *message,
                      ProtobufCBuffer     *buffer);
SscRotationvectorResponse *
       ssc_rotationvector_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssc_rotationvector_response__free_unpacked
                     (SscRotationvectorResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SscRotationvectorResponse_Closure)
                 (const SscRotationvectorResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssc_rotationvector_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ssc_2dsensor_2drotationvector_2eproto__INCLUDED */
