/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-proximity.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ssc-sensor-proximity.pb-c.h"
void   ssc_proximity_response__init
                     (SscProximityResponse         *message)
{
  static const SscProximityResponse init_value = SSC_PROXIMITY_RESPONSE__INIT;
  *message = init_value;
}
size_t ssc_proximity_response__get_packed_size
                     (const SscProximityResponse *message)
{
  assert(message->base.descriptor == &ssc_proximity_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssc_proximity_response__pack
                     (const SscProximityResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssc_proximity_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssc_proximity_response__pack_to_buffer
                     (const SscProximityResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssc_proximity_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SscProximityResponse *
       ssc_proximity_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SscProximityResponse *)
     protobuf_c_message_unpack (&ssc_proximity_response__descriptor,
                                allocator, len, data);
}
void   ssc_proximity_response__free_unpacked
                     (SscProximityResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssc_proximity_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssc_proximity_response_davinci__init
                     (SscProximityResponseDavinci         *message)
{
  static const SscProximityResponseDavinci init_value = SSC_PROXIMITY_RESPONSE_DAVINCI__INIT;
  *message = init_value;
}
size_t ssc_proximity_response_davinci__get_packed_size
                     (const SscProximityResponseDavinci *message)
{
  assert(message->base.descriptor == &ssc_proximity_response_davinci__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssc_proximity_response_davinci__pack
                     (const SscProximityResponseDavinci *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssc_proximity_response_davinci__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssc_proximity_response_davinci__pack_to_buffer
                     (const SscProximityResponseDavinci *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssc_proximity_response_davinci__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SscProximityResponseDavinci *
       ssc_proximity_response_davinci__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SscProximityResponseDavinci *)
     protobuf_c_message_unpack (&ssc_proximity_response_davinci__descriptor,
                                allocator, len, data);
}
void   ssc_proximity_response_davinci__free_unpacked
                     (SscProximityResponseDavinci *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssc_proximity_response_davinci__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssc_proximity_response__field_descriptors[3] =
{
  {
    "near",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SscProximityResponse, near),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SscProximityResponse, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accuracy",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SscProximityResponse, accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssc_proximity_response__field_indices_by_name[] = {
  2,   /* field[2] = accuracy */
  1,   /* field[1] = distance */
  0,   /* field[0] = near */
};
static const ProtobufCIntRange ssc_proximity_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ssc_proximity_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SscProximityResponse",
  "SscProximityResponse",
  "SscProximityResponse",
  "",
  sizeof(SscProximityResponse),
  3,
  ssc_proximity_response__field_descriptors,
  ssc_proximity_response__field_indices_by_name,
  1,  ssc_proximity_response__number_ranges,
  (ProtobufCMessageInit) ssc_proximity_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssc_proximity_response_davinci__field_descriptors[2] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SscProximityResponseDavinci, n_data),
    offsetof(SscProximityResponseDavinci, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accuracy",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SscProximityResponseDavinci, accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssc_proximity_response_davinci__field_indices_by_name[] = {
  1,   /* field[1] = accuracy */
  0,   /* field[0] = data */
};
static const ProtobufCIntRange ssc_proximity_response_davinci__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ssc_proximity_response_davinci__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SscProximityResponseDavinci",
  "SscProximityResponseDavinci",
  "SscProximityResponseDavinci",
  "",
  sizeof(SscProximityResponseDavinci),
  2,
  ssc_proximity_response_davinci__field_descriptors,
  ssc_proximity_response_davinci__field_indices_by_name,
  1,  ssc_proximity_response_davinci__number_ranges,
  (ProtobufCMessageInit) ssc_proximity_response_davinci__init,
  NULL,NULL,NULL    /* reserved[123] */
};
