/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-light.proto */

#ifndef PROTOBUF_C_ssc_2dsensor_2dlight_2eproto__INCLUDED
#define PROTOBUF_C_ssc_2dsensor_2dlight_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SscLightResponse SscLightResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Light Sensor specific response data.
 * @intensity: intensity in Lux [0] or raw sensor value [1].
 * @accuracy: how reliable the value is [0, 3]. Higher is more accurate, 0 is unreliable.
 */
struct  SscLightResponse
{
  ProtobufCMessage base;
  size_t n_intensity;
  float *intensity;
  int32_t accuracy;
};
#define SSC_LIGHT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssc_light_response__descriptor) \
    , 0,NULL, 0 }


/* SscLightResponse methods */
void   ssc_light_response__init
                     (SscLightResponse         *message);
size_t ssc_light_response__get_packed_size
                     (const SscLightResponse   *message);
size_t ssc_light_response__pack
                     (const SscLightResponse   *message,
                      uint8_t             *out);
size_t ssc_light_response__pack_to_buffer
                     (const SscLightResponse   *message,
                      ProtobufCBuffer     *buffer);
SscLightResponse *
       ssc_light_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssc_light_response__free_unpacked
                     (SscLightResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SscLightResponse_Closure)
                 (const SscLightResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssc_light_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ssc_2dsensor_2dlight_2eproto__INCLUDED */
