/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-accelerometer.proto */

#ifndef PROTOBUF_C_ssc_2dsensor_2daccelerometer_2eproto__INCLUDED
#define PROTOBUF_C_ssc_2dsensor_2daccelerometer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SscAccelerometerResponse SscAccelerometerResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * Accelerometer Sensor specific response data.
 * @acceleration: acceleration per axis in m/s²: X-axis [0], Y-axis [1], Z-axis [2].
 * @accuracy: how reliable the value is [0, 3]. Higher is more accurate, 0 is unreliable.
 */
struct  SscAccelerometerResponse
{
  ProtobufCMessage base;
  size_t n_acceleration;
  float *acceleration;
  int32_t accuracy;
};
#define SSC_ACCELEROMETER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssc_accelerometer_response__descriptor) \
    , 0,NULL, 0 }


/* SscAccelerometerResponse methods */
void   ssc_accelerometer_response__init
                     (SscAccelerometerResponse         *message);
size_t ssc_accelerometer_response__get_packed_size
                     (const SscAccelerometerResponse   *message);
size_t ssc_accelerometer_response__pack
                     (const SscAccelerometerResponse   *message,
                      uint8_t             *out);
size_t ssc_accelerometer_response__pack_to_buffer
                     (const SscAccelerometerResponse   *message,
                      ProtobufCBuffer     *buffer);
SscAccelerometerResponse *
       ssc_accelerometer_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssc_accelerometer_response__free_unpacked
                     (SscAccelerometerResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SscAccelerometerResponse_Closure)
                 (const SscAccelerometerResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssc_accelerometer_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ssc_2dsensor_2daccelerometer_2eproto__INCLUDED */
