/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-magnetometer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ssc-sensor-magnetometer.pb-c.h"
void   ssc_magnetometer_response__init
                     (SscMagnetometerResponse         *message)
{
  static const SscMagnetometerResponse init_value = SSC_MAGNETOMETER_RESPONSE__INIT;
  *message = init_value;
}
size_t ssc_magnetometer_response__get_packed_size
                     (const SscMagnetometerResponse *message)
{
  assert(message->base.descriptor == &ssc_magnetometer_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssc_magnetometer_response__pack
                     (const SscMagnetometerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssc_magnetometer_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssc_magnetometer_response__pack_to_buffer
                     (const SscMagnetometerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssc_magnetometer_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SscMagnetometerResponse *
       ssc_magnetometer_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SscMagnetometerResponse *)
     protobuf_c_message_unpack (&ssc_magnetometer_response__descriptor,
                                allocator, len, data);
}
void   ssc_magnetometer_response__free_unpacked
                     (SscMagnetometerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssc_magnetometer_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssc_magnetometer_response__field_descriptors[2] =
{
  {
    "magnetic_field",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SscMagnetometerResponse, n_magnetic_field),
    offsetof(SscMagnetometerResponse, magnetic_field),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accuracy",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SscMagnetometerResponse, accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssc_magnetometer_response__field_indices_by_name[] = {
  1,   /* field[1] = accuracy */
  0,   /* field[0] = magnetic_field */
};
static const ProtobufCIntRange ssc_magnetometer_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ssc_magnetometer_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SscMagnetometerResponse",
  "SscMagnetometerResponse",
  "SscMagnetometerResponse",
  "",
  sizeof(SscMagnetometerResponse),
  2,
  ssc_magnetometer_response__field_descriptors,
  ssc_magnetometer_response__field_indices_by_name,
  1,  ssc_magnetometer_response__number_ranges,
  (ProtobufCMessageInit) ssc_magnetometer_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
