/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ssc-sensor-accelerometer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ssc-sensor-accelerometer.pb-c.h"
void   ssc_accelerometer_response__init
                     (SscAccelerometerResponse         *message)
{
  static const SscAccelerometerResponse init_value = SSC_ACCELEROMETER_RESPONSE__INIT;
  *message = init_value;
}
size_t ssc_accelerometer_response__get_packed_size
                     (const SscAccelerometerResponse *message)
{
  assert(message->base.descriptor == &ssc_accelerometer_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssc_accelerometer_response__pack
                     (const SscAccelerometerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssc_accelerometer_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssc_accelerometer_response__pack_to_buffer
                     (const SscAccelerometerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssc_accelerometer_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SscAccelerometerResponse *
       ssc_accelerometer_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SscAccelerometerResponse *)
     protobuf_c_message_unpack (&ssc_accelerometer_response__descriptor,
                                allocator, len, data);
}
void   ssc_accelerometer_response__free_unpacked
                     (SscAccelerometerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssc_accelerometer_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssc_accelerometer_response__field_descriptors[2] =
{
  {
    "acceleration",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SscAccelerometerResponse, n_acceleration),
    offsetof(SscAccelerometerResponse, acceleration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accuracy",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SscAccelerometerResponse, accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssc_accelerometer_response__field_indices_by_name[] = {
  0,   /* field[0] = acceleration */
  1,   /* field[1] = accuracy */
};
static const ProtobufCIntRange ssc_accelerometer_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ssc_accelerometer_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SscAccelerometerResponse",
  "SscAccelerometerResponse",
  "SscAccelerometerResponse",
  "",
  sizeof(SscAccelerometerResponse),
  2,
  ssc_accelerometer_response__field_descriptors,
  ssc_accelerometer_response__field_indices_by_name,
  1,  ssc_accelerometer_response__number_ranges,
  (ProtobufCMessageInit) ssc_accelerometer_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
